config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from django.utils.translation import gettext_lazy as _

from config.views import favicon
from ganexa_event_manager import __version__ as current_version

admin.site.site_header = _("Ganexa Event Manager Admin v{}".format(current_version))
admin.site.site_title = _("Gaanexa Event Manager Portal v{}".format(current_version))
admin.site.index_title = _("Welcome to Ganexa Event Manager")

urlpatterns = i18n_patterns(
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ganexa_event_manager.users.urls", namespace="users")),
    path("golf/", include("ganexa_event_manager.golf.urls", namespace="golf")),
    path("events/", include("ganexa_event_manager.events.urls", namespace="events")),
    path("fasting/", include("ganexa_event_manager.fasting_track.urls", namespace="fasting-track")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    path("favicon.ico", favicon),
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ganexa_event_manager/events/urls.py
from django.urls import path

from .views import get_events, get_event_actions, ticket_form_view, delete_ticket_view, get_ticket_view

app_name = 'events'
urlpatterns = [
    # Patient CRUD urls
    path(r'events-for-user', get_events, name='events-for-user'),
    path(r'actions-for-event/<int:event_id>/', get_event_actions, name='actions-for-event'),
    path(r'ticket/create/<int:event_id>/', ticket_form_view, name='ticket-create'),
    path(r'ticket/delete/<int:ticket_id>/', delete_ticket_view, name='ticket-delete'),
    path(r'ticket/<int:ticket_id>/', get_ticket_view, name='ticket-details'),
]

ganexa_event_manager/fasting_track/urls.py
from django.urls import path

from .views import fasting_session_list_view, fasting_session_create_view, \
    fasting_session_update_view, fasting_session_delete_view, fasting_session_detail_view, fasting_session_main_view, \
    finish_fast, statistics_view, bar_chart_view

app_name = "fasting_track"
urlpatterns = [
    # FastingSession CRUD urls
    path(r'fasting-session/main/', fasting_session_main_view, name='main-fasting-session'),
    path(r'fasting-session/list/', fasting_session_list_view, name='list-fasting-session'),
    path(r'fasting-session/create/', fasting_session_create_view, name='create-fasting-session'),
    path(r'fasting-session/update/<int:pk>/', fasting_session_update_view, name='update-fasting-session'),
    path(r'fasting-session/delete/<int:pk>/', fasting_session_delete_view, name='delete-fasting-session'),
    path(r'fasting-session/<int:pk>/', fasting_session_detail_view, name='detail-fasting-session'),

    path('fasting-session/finish/<int:pk>/', finish_fast, name='finish-fasting-session'),
    path('fasting-session/statistics/', statistics_view, name='statistics-fasting-session'),
    path('fasting-session/chart/', bar_chart_view, name='chart-fasting-session')

]

ganexa_event_manager/golf/urls.py
from django.urls import path

from .views import range_hits_view, save_hit_view, list_player_hits_view, delete_range_hit, golf_club_stats_view

app_name = "golf"
urlpatterns = [
    path("range-hits/", view=range_hits_view, name="range-hits"),
    path("save-hit/", view=save_hit_view, name="save-hit"),
    path("player-hits/", view=list_player_hits_view, name="player-hits"),
    path("player-hit/delete/<int:pk>/", view=delete_range_hit, name="player-hit-delete"),
    path("golf-club/<int:pk>/", view=golf_club_stats_view, name="golf-club-stats"),
]

ganexa_event_manager/users/urls.py
from django.urls import path

from ganexa_event_manager.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

ganexa_event_manager/comp_time/models.py
from django.db import models

# Create your models here.
from ganexa_event_manager.core.models import TimedTask


class TimeRegister(TimedTask):
    pass

ganexa_event_manager/core/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from model_utils.models import TimeStampedModel
from django.utils.translation import gettext_lazy as _


class AuditableModel(models.Model):
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="created_%(class)s", null=True, on_delete=models.SET_NULL
    )
    modified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="modified_%(class)s", null=True, on_delete=models.SET_NULL
    )

    class Meta:
        abstract = True


class TimedTask(AuditableModel, TimeStampedModel):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('User'),
                              related_name='owned_%(class)s',
                              on_delete=models.CASCADE)
    start_date = models.DateTimeField(_('Start date'))
    end_date = models.DateTimeField(_('End date'), null=True, blank=True)
    duration = models.DurationField(_('Duration'), null=True, blank=True)
    comments = models.CharField(_('Comments'), max_length=180, null=True, blank=True)
    is_negative = models.BooleanField(_('Is negative'), default=False)

    class Meta:
        ordering = ('-start_date',)
        abstract = True

    @property
    def elapsed(self) -> float:
        if self.end_date is None:
            end_date = timezone.now()
        else:
            end_date = self.end_date
        if self.is_negative:
            elapsed_duration = self.start_date - end_date
        else:
            elapsed_duration = end_date - self.start_date

        return elapsed_duration

    def __str__(self):
        return f'{self.owner.username} {self.start_date} {self.duration}'

    def finish(self, commit: bool = True) -> float:
        self.end_date = timezone.now()
        self.duration = self.elapsed
        if commit:
            self.save()
        return self.duration

    def save(self, *args, **kwargs):
        self.duration = self.elapsed
        super(TimedTask, self).save(*args, **kwargs)

ganexa_event_manager/ex_training/forms.py
from django import forms


class ExerciseForm(forms.Form):
    pass

ganexa_event_manager/golf/forms.py
from django import forms

from ganexa_event_manager.golf.models import RangeHit


class RangeHitForm(forms.ModelForm):
    class Meta:
        model = RangeHit
        fields = (
            'course',
            'player',
            'club',
            'distance',
            'direction',
            'hit_classification',
        )

ganexa_event_manager/comp_time/views.py
from django.shortcuts import render

# Create your views here.

ganexa_event_manager/events/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from .forms import TicketForm
from .models import Event, Ticket

logger = logging.getLogger(__name__)


# @login_required
def get_events(request):
    template_name = 'events/partials/events_for_user.html'
    events = Event.objects.all()
    context = {'events': events}
    response = render(request, template_name, context)
    return response


@login_required
def get_event_actions(request, event_id):
    template_name = 'events/partials/event_buttons.html'
    try:
        event = Event.objects.get(id=event_id)
    except Event.DoesNotExist:
        event = None

    tickets = Ticket.objects.filter(owner=request.user, event__id=event_id)
    context = dict()
    context['event'] = event
    if tickets.count() == 0:
        context['ticket'] = None
    elif tickets.count() == 1:
        context['ticket'] = tickets.first()
    else:
        msg = f'User {request.user} has more than one ticket'
        logger.warning(msg)
        context['ticket'] = None
        context['error'] = msg
    response = render(request, template_name, context)
    return response


@login_required
def ticket_form_view(request, event_id):
    if request.method == 'GET':
        template_name = 'events/partials/ticket_form.html'
        try:
            event = Event.objects.get(id=event_id)
        except Event.DoesNotExist:
            event = None
        form = TicketForm(event=event, owner=request.user)
        context = {'form': form, 'event': event}
        response = render(request, template_name, context)
        return response
    if request.method == 'POST':
        form = TicketForm(data=request.POST)
        if form.is_valid():
            form.save()
            ticket = form.instance
            response = get_event_actions(request, ticket.event.id)
            return response
        else:
            return HttpResponse('Error')


@login_required
def delete_ticket_view(request, ticket_id):
    try:
        ticket = Ticket.objects.get(id=ticket_id)
    except Ticket.DoesNotExist:
        logger.error(f'Not ticket for id {ticket_id}')
    if ticket.owner == request.user:
        event = ticket.event
        ticket.delete()
        response = get_event_actions(request, event.id)
        return response
    else:
        logger.error('You cannot delete a ticket that you do not own')


@login_required
def get_ticket_view(request, ticket_id):
    try:
        ticket = Ticket.objects.get(id=ticket_id)
        template_name = 'events/partials/ticket_detail.html'
        context = {'ticket': ticket}
        response = render(request, template_name, context)
        return response
    except Ticket.DoesNotExist:
        logger.error(f'No ticket for {ticket_id}')

ganexa_event_manager/ex_training/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView, DetailView, UpdateView

from ganexa_event_manager.ex_training.forms import ExerciseForm
from ganexa_event_manager.ex_training.models import Exercise


class ExerciseCreateView(LoginRequiredMixin, CreateView):
    model = Exercise
    form_class = ExerciseForm
    success_url = reverse_lazy('ex-training:list-exercise')


exercise_create_view = ExerciseCreateView.as_view()


class ExerciseUpdateView(LoginRequiredMixin, UpdateView):
    model = Exercise
    form_class = ExerciseForm
    success_url = reverse_lazy('ex-training:list-exercise')


exercise_update_view = ExerciseUpdateView.as_view()


class ExerciseListView(LoginRequiredMixin, ListView):
    model = Exercise
    context_object_name = 'exercise_list'
    paginate_by = 10


exercise_list_view = ExerciseListView.as_view()


class ExerciseDeleteView(LoginRequiredMixin, DeleteView):
    model = Exercise
    success_url = reverse_lazy('ex-training:list-exercise')


exercise_delete_view = ExerciseDeleteView.as_view()


class ExerciseDetailView(LoginRequiredMixin, DetailView):
    model = Exercise


exercise_detail_view = ExerciseDetailView.as_view()

ganexa_event_manager/fasting_track/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView, TemplateView
import plotly.express as px
from .forms import FastingSessionForm
from .models import FastingSession


class FastingSessionMainView(TemplateView):
    template_name = 'fasting_track/fasting_track_index.html'


fasting_session_main_view = FastingSessionMainView.as_view()


class FastingSessionCreateView(LoginRequiredMixin, CreateView):
    model = FastingSession
    form_class = FastingSessionForm
    success_url = reverse_lazy('fasting-track:list-fasting-session')

    def get_form_kwargs(self):
        kwargs = super(FastingSessionCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


fasting_session_create_view = FastingSessionCreateView.as_view()


class FastingSessionUpdateView(LoginRequiredMixin, UpdateView):
    model = FastingSession
    form_class = FastingSessionForm
    success_url = reverse_lazy('fasting-track:list-fasting-session')

    def get_form_kwargs(self):
        kwargs = super(FastingSessionUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


fasting_session_update_view = FastingSessionUpdateView.as_view()


class FastingSessionListView(LoginRequiredMixin, ListView):
    model = FastingSession
    context_object_name = 'fasting_session_list'
    paginate_by = 5

    def get_queryset(self):
        qs = super(FastingSessionListView, self).get_queryset()
        return qs.filter(user=self.request.user)


fasting_session_list_view = FastingSessionListView.as_view()


class FastingSessionDeleteView(LoginRequiredMixin, DeleteView):
    model = FastingSession
    success_url = reverse_lazy('fasting-track:list-fasting-session')


fasting_session_delete_view = FastingSessionDeleteView.as_view()


class FastingSessionDetailView(LoginRequiredMixin, DetailView):
    model = FastingSession


fasting_session_detail_view = FastingSessionDetailView.as_view()


@login_required
def finish_fast(request: HttpRequest, pk: int) -> HttpResponse:
    try:
        fasting_session = FastingSession.objects.get(user=request.user, id=pk)
        fasting_session.finish()
        url = reverse('fasting_track:detail-fasting-session', kwargs={'pk': fasting_session.pk})
        response = redirect(url)
        return response
    except FastingSession.DoesNotExist:
        pass


@require_http_methods(['GET'])
@login_required
def statistics_view(request: HttpRequest) -> HttpResponse:
    average_duration = FastingSession.objects.average_hours(user=request.user)
    context = {'average_duration': average_duration,
               'longest_fasting_session': FastingSession.objects.longest_fasting_session(user=request.user)}
    template_name = 'fasting_track/partials/statistics.html'
    response = render(request, template_name, context)
    return response

@require_http_methods(['GET'])
@login_required
def bar_chart_view(request: HttpRequest) -> HttpResponse:
    context = dict()
    qs = FastingSession.objects.filter(user=request.user)[:7]
    import time
    start = time.time()
    fig = px.bar(
        x=[fs.start_date for fs in qs],
        y=[fs.duration for fs in qs]
    )
    context['building_chart'] = time.time() - start
    start = time.time()
    chart = fig.to_html(full_html=False) #, include_plotlyjs=False)
    context['building_chart_to_html'] = time.time() - start
    context['chart'] = chart
    template_name = 'fasting_track/partials/bar_chart.html'

    response = render(request, template_name, context)
    return response

ganexa_event_manager/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

ganexa_event_manager/templates/fasting_track/fasting_track_index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <div id="main">
    <div id="fast-form">
      {% include 'fasting_track/partials/fasting_form.html' %}
    </div>
  </div>
{% endblock %}

ganexa_event_manager/templates/fasting_track/fastingsession_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    <h1 data-cy="delete-title">{% trans 'Confirm delete' %}</h1>
    <form method="post">
        {% csrf_token %}
        <p>
            {% blocktrans with start_date=object.start_date duration=object.duration %}
                Are you sure you want to delete your fasting session of {{ start_date }} that lasted {{ duration }} ?
            {% endblocktrans %}
        </p>
        <div class="control-group">
            <div class="controls">
                <a href="{% url 'fasting-track:list-fasting-session' %}" class="btn btn-primary">{% trans 'Cancel' %}</a>
                <input type="submit" value="{% trans 'Confirm' %}" class="btn btn-danger" id="delete-btn" data-cy="submit">
            </div>
        </div>

    </form>

{% endblock %}

ganexa_event_manager/templates/fasting_track/fastingsession_detail.html
{% extends "base.html" %}
{% load i18n fasting_tags %}

{% block content %}
  <h3>{% trans 'Current fast' %}</h3>
  <div class="row">
    <div class="col-3">
      {% trans 'Start date' %}
    </div>
    <div class="col-3">
      {{ object.start_date|date:'Y-m-d H:i' }}
    </div>
    {% if object.end_date is not None %}
      <div class="col-3">
        {% trans 'End date' %}
      </div>
      <div class="col-3">
        {{ object.end_date|date:'Y-m-d H:i' }}
      </div>
    {% endif %}
  </div>
  <div class="row">
    <div class="col-3">
      {% trans 'Target duration' %}
    </div>
    <div class="col-3">
      {{ object.target_duration }}
    </div>
  </div>
  <div class="row">
    <div class="col-3">
      {% trans 'Completed' %}
    </div>
    <div class="col-3">
      {{ object.completed|percentage }}
    </div>
  </div>
  <div class="row">
    <div class="col-3">
      {% trans 'Duration' %}
    </div>
    <div class="col-3">
      {{ object.current_duration|hours }}
    </div>
  </div>
  <div class="row">
    {% if not object.end_date %}
      <div class="col-6">
        <a class="btn btn-danger"
           href="{% url 'fasting-track:finish-fasting-session' object.pk %}">{% trans 'Finish fast' %}</a>
      </div>
    {% endif %}
    <div class="col-6 d-flex justify-content-end">
      <a href="{% url 'fasting-track:list-fasting-session' %}"
         class="btn btn-primary"><i class="bi bi-card-list"></i></a>
    </div>
  </div>
  <div class="row" hx-get="{% url 'fasting-track:statistics-fasting-session' %}" hx-trigger="once"
       hx-target="#statistics"
       id="statistics">
  </div>
  {% include 'fasting_track/partials/bar_chart.html' %}
{% endblock %}

ganexa_event_manager/templates/fasting_track/fastingsession_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
  <form class="form-horizontal" method="post" action="" id="fasting-session-form">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
            <div class="controls">
                <a href="{% url 'fasting-track:list-fasting-session' %}" class="btn btn-primary">{% trans 'Cancel' %}</a>
                <button type="submit" class="btn btn-primary" id="save_button">{% trans 'Save' %}</button>
            </div>
        </div>
{% endblock %}

{% block inline_javascript %}
  {{ block.super }}
  <script>
    $('#id_start_date').datetimepicker({
      format: 'yyyy-mm-dd HH:MM:ss'
    });
  </script>
{% endblock %}

ganexa_event_manager/templates/fasting_track/fastingsession_list.html
{% extends "base.html" %}
{% load i18n fasting_tags %}

{% block content %}
  <div class="row">
    <div class="col-8">
      <h2>{% trans 'Fasting sessions' %}</h2>
    </div>
    <div class="col-4">
      <a href="{% url 'fasting-track:create-fasting-session' %}" class="btn btn-primary"><i
        class="bi bi-plus-circle"></i></a>
    </div>
  </div>
  <div class="row">
    <div class="col-3 d-none d-sm-block"> Start</div>
    <div class="col-2 d-none d-sm-block"> Target</div>
    <div class="col-2 d-none d-sm-block"> Duration</div>
    <div class="col-2 d-none d-sm-block"> Percentage</div>
    <div class="col-3 d-none d-sm-block"> Actions</div>
  </div>

  <div id="fast-session-list">
  {% for session in object_list %}
    {% if session.end_date %}
      <div class="row p-1 border border-top border-bottom">
    {% else %}
      <div class="row p-1 text-danger border border-top border-bottom">
    {% endif %}
  <div class="col-5 col-md-3">
    {{ session.start_date|date:'Y-m-d H:i' }}
  </div>
  <div class="col-2 d-none d-sm-block">
    {{ session.target_duration|hours }}
  </div>
  <div class="col-2 col-md-2">
    {{ session.current_duration|hours }}
  </div>
  <div class="col-2 col-md-2">
    {{ session.completed|percentage }}
  </div>
  <div class="col-6 col-md-3">
    <a href="{% url 'fasting-track:detail-fasting-session' session.id %}" class="btn btn-primary">
      <i class="bi bi-eye"></i>
    </a>
    <a href="{% url 'fasting-track:update-fasting-session' session.id %}" class="btn btn-success">
      <i class="bi bi-pencil"></i>
    </a>
    <a href="{% url 'fasting-track:delete-fasting-session' session.id %}" class="btn btn-danger">
      <i class="bi bi-trash"></i>
    </a>
  </div>
  </div>
  {% endfor %}
</div>
  <div class="row">
    <div class="col-12">
      {% include 'snippets/pagination_bar.html' %}
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <a class="btn btn-primary" href="{% url 'fasting-track:list-fasting-session' %}">Refresh</a>
    </div>
  </div>
{% endblock %}