config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from django.utils.translation import gettext_lazy as _

from config.views import favicon
from ganexa_event_manager import __version__ as current_version

admin.site.site_header = _("Ganexa Event Manager Admin v{}".format(current_version))
admin.site.site_title = _("Gaanexa Event Manager Portal v{}".format(current_version))
admin.site.index_title = _("Welcome to Ganexa Event Manager")

urlpatterns = i18n_patterns(
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ganexa_event_manager.users.urls", namespace="users")),
    path("golf/", include("ganexa_event_manager.golf.urls", namespace="golf")),
    path("events/", include("ganexa_event_manager.events.urls", namespace="events")),
    path("fasting/", include("ganexa_event_manager.fasting_track.urls", namespace="fasting-track")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    path("favicon.ico", favicon),
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ganexa_event_manager/events/urls.py
from django.urls import path

from .views import get_events, get_event_actions, ticket_form_view, delete_ticket_view, get_ticket_view

app_name = 'events'
urlpatterns = [
    # Patient CRUD urls
    path(r'events-for-user', get_events, name='events-for-user'),
    path(r'actions-for-event/<int:event_id>/', get_event_actions, name='actions-for-event'),
    path(r'ticket/create/<int:event_id>/', ticket_form_view, name='ticket-create'),
    path(r'ticket/delete/<int:ticket_id>/', delete_ticket_view, name='ticket-delete'),
    path(r'ticket/<int:ticket_id>/', get_ticket_view, name='ticket-details'),
]

ganexa_event_manager/fasting_track/urls.py
from django.urls import path

from .views import fasting_session_list_view, fasting_session_create_view, \
    fasting_session_update_view, fasting_session_delete_view, fasting_session_detail_view, fasting_session_main_view, \
    finish_fast, statistics_view, bar_chart_view

app_name = "fasting_track"
urlpatterns = [
    # FastingSession CRUD urls
    path(r'fasting-session/main/', fasting_session_main_view, name='main-fasting-session'),
    path(r'fasting-session/list/', fasting_session_list_view, name='list-fasting-session'),
    path(r'fasting-session/create/', fasting_session_create_view, name='create-fasting-session'),
    path(r'fasting-session/update/<int:pk>/', fasting_session_update_view, name='update-fasting-session'),
    path(r'fasting-session/delete/<int:pk>/', fasting_session_delete_view, name='delete-fasting-session'),
    path(r'fasting-session/<int:pk>/', fasting_session_detail_view, name='detail-fasting-session'),

    path('fasting-session/finish/<int:pk>/', finish_fast, name='finish-fasting-session'),
    path('fasting-session/statistics/', statistics_view, name='statistics-fasting-session'),
    path('fasting-session/chart/', bar_chart_view, name='chart-fasting-session')

]

ganexa_event_manager/golf/urls.py
from django.urls import path

from .views import range_hits_view, save_hit_view, list_player_hits_view, delete_range_hit, golf_club_stats_view

app_name = "golf"
urlpatterns = [
    path("range-hits/", view=range_hits_view, name="range-hits"),
    path("save-hit/", view=save_hit_view, name="save-hit"),
    path("player-hits/", view=list_player_hits_view, name="player-hits"),
    path("player-hit/delete/<int:pk>/", view=delete_range_hit, name="player-hit-delete"),
    path("golf-club/<int:pk>/", view=golf_club_stats_view, name="golf-club-stats"),
]

ganexa_event_manager/users/urls.py
from django.urls import path

from ganexa_event_manager.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

ganexa_event_manager/ex_training/forms.py
from django import forms


class ExerciseForm(forms.Form):
    pass

ganexa_event_manager/comp_time/views.py
from django.shortcuts import render

# Create your views here.

ganexa_event_manager/events/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from .forms import TicketForm
from .models import Event, Ticket

logger = logging.getLogger(__name__)


# @login_required
def get_events(request):
    template_name = 'events/partials/events_for_user.html'
    events = Event.objects.all()
    context = {'events': events}
    response = render(request, template_name, context)
    return response


@login_required
def get_event_actions(request, event_id):
    template_name = 'events/partials/event_buttons.html'
    try:
        event = Event.objects.get(id=event_id)
    except Event.DoesNotExist:
        event = None

    tickets = Ticket.objects.filter(owner=request.user, event__id=event_id)
    context = dict()
    context['event'] = event
    if tickets.count() == 0:
        context['ticket'] = None
    elif tickets.count() == 1:
        context['ticket'] = tickets.first()
    else:
        msg = f'User {request.user} has more than one ticket'
        logger.warning(msg)
        context['ticket'] = None
        context['error'] = msg
    response = render(request, template_name, context)
    return response


@login_required
def ticket_form_view(request, event_id):
    if request.method == 'GET':
        template_name = 'events/partials/ticket_form.html'
        try:
            event = Event.objects.get(id=event_id)
        except Event.DoesNotExist:
            event = None
        form = TicketForm(event=event, owner=request.user)
        context = {'form': form, 'event': event}
        response = render(request, template_name, context)
        return response
    if request.method == 'POST':
        form = TicketForm(data=request.POST)
        if form.is_valid():
            form.save()
            ticket = form.instance
            response = get_event_actions(request, ticket.event.id)
            return response
        else:
            return HttpResponse('Error')


@login_required
def delete_ticket_view(request, ticket_id):
    try:
        ticket = Ticket.objects.get(id=ticket_id)
    except Ticket.DoesNotExist:
        logger.error(f'Not ticket for id {ticket_id}')
    if ticket.owner == request.user:
        event = ticket.event
        ticket.delete()
        response = get_event_actions(request, event.id)
        return response
    else:
        logger.error('You cannot delete a ticket that you do not own')


@login_required
def get_ticket_view(request, ticket_id):
    try:
        ticket = Ticket.objects.get(id=ticket_id)
        template_name = 'events/partials/ticket_detail.html'
        context = {'ticket': ticket}
        response = render(request, template_name, context)
        return response
    except Ticket.DoesNotExist:
        logger.error(f'No ticket for {ticket_id}')

ganexa_event_manager/ex_training/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView, DetailView, UpdateView

from ganexa_event_manager.ex_training.forms import ExerciseForm
from ganexa_event_manager.ex_training.models import Exercise


class ExerciseCreateView(LoginRequiredMixin, CreateView):
    model = Exercise
    form_class = ExerciseForm
    success_url = reverse_lazy('ex-training:list-exercise')


exercise_create_view = ExerciseCreateView.as_view()


class ExerciseUpdateView(LoginRequiredMixin, UpdateView):
    model = Exercise
    form_class = ExerciseForm
    success_url = reverse_lazy('ex-training:list-exercise')


exercise_update_view = ExerciseUpdateView.as_view()


class ExerciseListView(LoginRequiredMixin, ListView):
    model = Exercise
    context_object_name = 'exercise_list'
    paginate_by = 10


exercise_list_view = ExerciseListView.as_view()


class ExerciseDeleteView(LoginRequiredMixin, DeleteView):
    model = Exercise
    success_url = reverse_lazy('ex-training:list-exercise')


exercise_delete_view = ExerciseDeleteView.as_view()


class ExerciseDetailView(LoginRequiredMixin, DetailView):
    model = Exercise


exercise_detail_view = ExerciseDetailView.as_view()

ganexa_event_manager/fasting_track/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView, TemplateView
import plotly.express as px
from .forms import FastingSessionForm
from .models import FastingSession


class FastingSessionMainView(TemplateView):
    template_name = 'fasting_track/fasting_track_index.html'


fasting_session_main_view = FastingSessionMainView.as_view()


class FastingSessionCreateView(LoginRequiredMixin, CreateView):
    model = FastingSession
    form_class = FastingSessionForm
    success_url = reverse_lazy('fasting-track:list-fasting-session')

    def get_form_kwargs(self):
        kwargs = super(FastingSessionCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


fasting_session_create_view = FastingSessionCreateView.as_view()


class FastingSessionUpdateView(LoginRequiredMixin, UpdateView):
    model = FastingSession
    form_class = FastingSessionForm
    success_url = reverse_lazy('fasting-track:list-fasting-session')

    def get_form_kwargs(self):
        kwargs = super(FastingSessionUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


fasting_session_update_view = FastingSessionUpdateView.as_view()


class FastingSessionListView(LoginRequiredMixin, ListView):
    model = FastingSession
    context_object_name = 'fasting_session_list'
    paginate_by = 5

    def get_queryset(self):
        qs = super(FastingSessionListView, self).get_queryset()
        return qs.filter(user=self.request.user)


fasting_session_list_view = FastingSessionListView.as_view()


class FastingSessionDeleteView(LoginRequiredMixin, DeleteView):
    model = FastingSession
    success_url = reverse_lazy('fasting-track:list-fasting-session')


fasting_session_delete_view = FastingSessionDeleteView.as_view()


class FastingSessionDetailView(LoginRequiredMixin, DetailView):
    model = FastingSession


fasting_session_detail_view = FastingSessionDetailView.as_view()


@login_required
def finish_fast(request: HttpRequest, pk: int) -> HttpResponse:
    try:
        fasting_session = FastingSession.objects.get(user=request.user, id=pk)
        fasting_session.finish()
        url = reverse('fasting_track:detail-fasting-session', kwargs={'pk': fasting_session.pk})
        response = redirect(url)
        return response
    except FastingSession.DoesNotExist:
        pass


@require_http_methods(['GET'])
@login_required
def statistics_view(request: HttpRequest) -> HttpResponse:
    average_duration = FastingSession.objects.average_hours(user=request.user)
    context = {'average_duration': average_duration,
               'longest_fasting_session': FastingSession.objects.longest_fasting_session(user=request.user)}
    template_name = 'fasting_track/partials/statistics.html'
    response = render(request, template_name, context)
    return response

@require_http_methods(['GET'])
@login_required
def bar_chart_view(request: HttpRequest) -> HttpResponse:
    context = dict()
    qs = FastingSession.objects.filter(user=request.user)[:7]
    import time
    start = time.time()
    fig = px.bar(
        x=[fs.start_date for fs in qs],
        y=[fs.duration for fs in qs]
    )
    context['building_chart'] = time.time() - start
    start = time.time()
    chart = fig.to_html(full_html=False) #, include_plotlyjs=False)
    context['building_chart_to_html'] = time.time() - start
    context['chart'] = chart
    template_name = 'fasting_track/partials/bar_chart.html'

    response = render(request, template_name, context)
    return response

ganexa_event_manager/golf/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
from django.shortcuts import render
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from django.views.generic import TemplateView

from .forms import RangeHitForm
from .models import GolfClub, RangeHit, GolfCourse


class RangeHitsView(TemplateView):
    template_name = 'golf/range_hits.html'

    def get_context_data(self, **kwargs):
        player = self.request.user
        ctx = super(RangeHitsView, self).get_context_data(**kwargs)

        golf_clubs = GolfClub.objects.filter(player=player).annotate(average_distance=Avg('range_hits__distance'))
        ctx['golf_clubs'] = golf_clubs
        ctx['directions'] = RangeHit.DIRECTION_CHOICES

        return ctx


range_hits_view = RangeHitsView.as_view()


@login_required
def save_hit_view(request):
    form_dict = request.POST.copy()
    form_dict['player'] = request.user
    form_dict['course'] = GolfCourse.objects.first()
    print(f'>> hit dictionary {form_dict}')
    form = RangeHitForm(data=form_dict)
    if form.is_valid():
        form.save()
    else:
        print(form.errors)
    template_name = 'golf/partials/stats.html'
    today = timezone.now().date()
    qs = RangeHit.objects.filter(player=request.user, created__startswith=today)
    context = {'hits': qs[:10], 'hit_count': qs.count()}
    response = render(request, template_name, context)
    return response


@login_required
def list_player_hits_view(request):
    template_name = 'golf/partials/stats.html'
    today = timezone.now().date()
    qs = RangeHit.objects.filter(player=request.user, created__startswith=today)
    context = {'hits': qs[:10], 'hit_count': qs.count()}
    response = render(request, template_name, context)
    return response


@require_http_methods(['DELETE'])
@login_required
def delete_range_hit(request, pk):
    try:
        range_hit = RangeHit.objects.get(pk=pk)
        if range_hit.player == request.user:
            range_hit.delete()
    except RangeHit.DoesNotExist:
        pass
    return list_player_hits_view(request)


@require_http_methods(['GET'])
@login_required
def golf_club_stats_view(request, pk):
    player = request.user
    try:
        golf_club = GolfClub.objects.get(player=player, pk=pk).annotate(average_distance=Avg('range_hits__distance'))
        context = {'golf_club': golf_club }
        template_name = 'golf/partials/golf_club_stats.html'
        response = render(request, template_name, context)
        return response
    except GolfClub.DoesNotExist:
        pass

ganexa_event_manager/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

ganexa_event_manager/templates/base.html
{% load static i18n %}
{% load golf_tags %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Ganexa Event Manager{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="App to manage Ganexa events and tickets">
  <meta name="author" content="Luis C. Berrocal">

  <link rel="icon" href="/favicon.ico">

  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css"
          integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
  ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
    <!-- Bootstrap JS -->
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"
            integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->
    <script src="https://unpkg.com/htmx.org@1.7.0"
            integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo"
            crossorigin="anonymous"></script>
    <script defer src="https://unpkg.com/alpinejs@3.9.1/dist/cdn.min.js"></script>

    <!-- place project specific Javascript in this file -->
    <script defer src="{% static 'js/project.js' %}"></script>

  {% endblock javascript %}

</head>

<body>

<div class="mb-1">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Ganexa Event Manager</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'users:detail' request.user.username %}">{% translate "My Profile" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
            </li>
          {% else %}
            {% if ACCOUNT_ALLOW_REGISTRATION %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
              </li>
            {% endif %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

</div>

<div class="container">

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}

  {% block content %}
    <h2>{% trans "Welcome to our events portal" %}</h2>
    <div class="row">
      <div class="col-sm-12">
        <div class="container" id="events" hx-get="{% url 'events:events-for-user' %}" hx-target="#events"
             hx-trigger="load" hx-swap-oob="true">
        </div>
      </div>
    </div>
    {% if not request.user.is_authenticated %}
      <div class="row">
        <div class="col-6">
          <a href="{% url 'account_login' %}" class="btn btn-primary">{% trans 'Sign In' %}</a>
        </div>
        <div class="col-6">
          <a href="{% url 'account_signup' %}" class="btn btn-primary">{% trans 'Sign Up' %}</a>
        </div>
      </div>
    {% else %}
      {% if request.user|is_golfer %}
        <div class="row">
          <div class="col-12">
            <a href="{% url 'golf:range-hits' %}" class="btn btn-primary">{% trans 'Golf' %}</a>
          </div>
        </div>
      {% endif %}
      <div class="row">
      <div class="col-12">
        <a href="{% url 'fasting_track:list-fasting-session' %}" class="btn btn-primary">{% trans 'Fasting' %}</a>
      </div>
      </div>
    {% endif %}
  {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
  {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
{% endblock inline_javascript %}
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>
</body>
</html>